URL_BASE = "http://127.0.0.1:8080"
URL_STARTWATCHSERVER = "/accesscontrol/startwatchserver"
URL_STOPWATCHSERVER = "/accesscontrol/stopwatchserver"
URL_QUERYPERMIT = "/accesscontrol/querypermit"
URL_ADDPERMIT = "/accesscontrol/addpermit"
URL_DELPERMIT = "/accesscontrol/delpermit"
